"""
app/api/v1/routers/receipts.py
================================
GET /donations/{donation_id}/receipt  — returns a PDF receipt

Uses fpdf2 (lightweight, no system dependencies).
Install: pip install fpdf2
"""
import uuid
from fastapi import APIRouter, Depends, HTTPException
from fastapi.responses import Response
from sqlalchemy.ext.asyncio import AsyncSession

from app.core.deps import get_db, get_current_active_user
from app.models.donation import Donation, TransactionStatus
from app.models.user import User
from app.models.crowdfunding import Campaign

router = APIRouter(prefix="/donations", tags=["Receipts"])


def _build_pdf(donation: Donation, campaign: Campaign, donor: User) -> bytes:
    """Generate a PDF receipt using fpdf2."""
    try:
        from fpdf import FPDF
    except ImportError:
        raise HTTPException(
            status_code=503,
            detail="PDF generation unavailable — fpdf2 not installed"
        )

    pdf = FPDF()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=15)

    # ── Header ────────────────────────────────────────────────────────────────
    pdf.set_fill_color(124, 58, 237)   # purple
    pdf.rect(0, 0, 210, 40, "F")

    pdf.set_font("Helvetica", "B", 26)
    pdf.set_text_color(255, 255, 255)
    pdf.set_xy(10, 8)
    pdf.cell(0, 12, "ThankGiving", ln=True)

    pdf.set_font("Helvetica", "", 12)
    pdf.set_xy(10, 22)
    pdf.cell(0, 8, "Donation Receipt", ln=True)

    # ── Receipt ID + Date ─────────────────────────────────────────────────────
    pdf.set_text_color(50, 50, 50)
    pdf.set_xy(10, 50)
    pdf.set_font("Helvetica", "B", 11)
    pdf.cell(60, 8, "Receipt ID:", ln=False)
    pdf.set_font("Helvetica", "", 11)
    pdf.cell(0, 8, str(donation.id), ln=True)

    pdf.set_x(10)
    pdf.set_font("Helvetica", "B", 11)
    pdf.cell(60, 8, "Date:", ln=False)
    pdf.set_font("Helvetica", "", 11)
    pdf.cell(0, 8, donation.created_at.strftime("%d %B %Y, %H:%M UTC"), ln=True)

    # ── Divider ───────────────────────────────────────────────────────────────
    pdf.set_draw_color(200, 200, 200)
    pdf.set_line_width(0.5)
    pdf.line(10, pdf.get_y() + 3, 200, pdf.get_y() + 3)
    pdf.ln(8)

    # ── Donor Info ───────────────────────────────────────────────────────────
    pdf.set_font("Helvetica", "B", 13)
    pdf.set_text_color(124, 58, 237)
    pdf.cell(0, 8, "Donor Information", ln=True)
    pdf.set_text_color(50, 50, 50)
    pdf.set_font("Helvetica", "", 11)
    pdf.cell(0, 7, f"Name: {donor.full_name or 'Anonymous'}", ln=True)
    pdf.cell(0, 7, f"Email: {donor.email}", ln=True)
    pdf.ln(4)

    # ── Campaign Info ─────────────────────────────────────────────────────────
    pdf.set_font("Helvetica", "B", 13)
    pdf.set_text_color(124, 58, 237)
    pdf.cell(0, 8, "Campaign", ln=True)
    pdf.set_text_color(50, 50, 50)
    pdf.set_font("Helvetica", "", 11)
    pdf.cell(0, 7, f"Title: {campaign.title}", ln=True)
    pdf.cell(0, 7, f"Campaign ID: {campaign.id}", ln=True)
    pdf.ln(4)

    # ── Amount Box ───────────────────────────────────────────────────────────
    pdf.set_fill_color(245, 243, 255)
    pdf.set_draw_color(124, 58, 237)
    pdf.set_line_width(0.8)
    y = pdf.get_y()
    pdf.rect(10, y, 190, 25, "FD")
    pdf.set_xy(15, y + 5)
    pdf.set_font("Helvetica", "B", 15)
    pdf.set_text_color(124, 58, 237)
    pdf.cell(100, 10, "Total Donated:")
    pdf.set_font("Helvetica", "B", 18)
    pdf.cell(0, 10, f"{donation.currency_code} {float(donation.amount):,.2f}", ln=True)
    pdf.ln(10)

    # ── Status ────────────────────────────────────────────────────────────────
    pdf.set_text_color(50, 50, 50)
    pdf.set_font("Helvetica", "B", 11)
    pdf.cell(60, 8, "Transaction Status:", ln=False)
    pdf.set_font("Helvetica", "", 11)
    pdf.cell(0, 8, donation.transaction_status.value.upper(), ln=True)

    if donation.donor_message:
        pdf.ln(4)
        pdf.set_font("Helvetica", "B", 11)
        pdf.cell(0, 8, "Your Message:", ln=True)
        pdf.set_font("Helvetica", "I", 10)
        pdf.multi_cell(0, 7, f'"{donation.donor_message}"')

    # ── Footer ────────────────────────────────────────────────────────────────
    pdf.set_y(-30)
    pdf.set_font("Helvetica", "I", 9)
    pdf.set_text_color(150, 150, 150)
    pdf.cell(0, 6, "This receipt is auto-generated by ThankGiving platform.", ln=True, align="C")
    pdf.cell(0, 6, "Please keep this for your tax records.", ln=True, align="C")

    return bytes(pdf.output())


@router.get("/{donation_id}/receipt")
async def download_receipt(
    donation_id: uuid.UUID,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_active_user),
):
    """Download PDF receipt for a completed donation."""
    donation = await db.get(Donation, donation_id)
    if not donation:
        raise HTTPException(status_code=404, detail="Donation not found")
    if donation.donor_id != current_user.id:
        raise HTTPException(status_code=403, detail="Not your donation")
    if donation.transaction_status != TransactionStatus.COMPLETED:
        raise HTTPException(status_code=400, detail="Receipt only available for completed donations")

    campaign = await db.get(Campaign, donation.campaign_id)
    if not campaign:
        raise HTTPException(status_code=404, detail="Campaign not found")

    pdf_bytes = _build_pdf(donation, campaign, current_user)

    return Response(
        content=pdf_bytes,
        media_type="application/pdf",
        headers={
            "Content-Disposition": f'attachment; filename="receipt-{donation_id}.pdf"',
            "Content-Length": str(len(pdf_bytes)),
        },
    )
