"""initial_schema_all_tables

Revision ID: 687f6a6d21d1
Revises: 
Create Date: 2026-06-29 05:42:02.666706+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '687f6a6d21d1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('user_type', sa.Enum('INDIVIDUAL', 'ORGANIZATION', 'ADMIN', name='usertype'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('organizations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('org_type', sa.Enum('NGO', 'NONPROFIT', 'COMMUNITY', 'SOCIAL_ENTERPRISE', 'EDUCATIONAL', name='orgtype'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('website_url', sa.String(length=500), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('contact_phone', sa.String(length=20), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('country_code', sa.String(length=2), nullable=True),
    sa.Column('verification_status', sa.Enum('UNVERIFIED', 'PENDING', 'VERIFIED', 'REJECTED', name='verificationstatus'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_name'), 'organizations', ['name'], unique=False)
    op.create_index(op.f('ix_organizations_owner_id'), 'organizations', ['owner_id'], unique=False)
    op.create_table('campaigns',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.Enum('EDUCATION', 'HEALTH', 'ENVIRONMENT', 'DISASTER_RELIEF', 'COMMUNITY', 'ARTS', 'OTHER', name='campaigncategory'), nullable=False),
    sa.Column('target_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('raised_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'COMPLETED', 'CANCELLED', 'ARCHIVED', name='campaignstatus'), nullable=False),
    sa.Column('backer_count', sa.Integer(), nullable=False),
    sa.Column('is_flexible_funding', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaigns_organization_id'), 'campaigns', ['organization_id'], unique=False)
    op.create_index(op.f('ix_campaigns_status'), 'campaigns', ['status'], unique=False)
    op.create_table('in_kind_donations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('donor_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('item_name', sa.String(length=255), nullable=False),
    sa.Column('item_description', sa.Text(), nullable=True),
    sa.Column('category', sa.Enum('CLOTHING', 'FOOD', 'ELECTRONICS', 'FURNITURE', 'BOOKS', 'MEDICAL', 'TOYS', 'TOOLS', 'OTHER', name='itemcategory'), nullable=False),
    sa.Column('condition', sa.Enum('NEW', 'GENTLY_USED', 'FAIR', 'POOR', name='itemcondition'), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_of_measure', sa.String(length=50), nullable=False),
    sa.Column('estimated_value', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('pickup_address', sa.String(length=500), nullable=True),
    sa.Column('pickup_city', sa.String(length=100), nullable=True),
    sa.Column('pickup_available_from', sa.Date(), nullable=True),
    sa.Column('pickup_available_until', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('OFFERED', 'ACCEPTED', 'REJECTED', 'PICKED_UP', 'RECEIVED', 'DISTRIBUTED', 'CANCELLED', name='inkindstatus'), nullable=False),
    sa.Column('coordinator_notes', sa.Text(), nullable=True),
    sa.Column('confirmed_pickup_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['donor_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_in_kind_donations_category'), 'in_kind_donations', ['category'], unique=False)
    op.create_index(op.f('ix_in_kind_donations_donor_id'), 'in_kind_donations', ['donor_id'], unique=False)
    op.create_index(op.f('ix_in_kind_donations_organization_id'), 'in_kind_donations', ['organization_id'], unique=False)
    op.create_index(op.f('ix_in_kind_donations_status'), 'in_kind_donations', ['status'], unique=False)
    op.create_table('volunteer_opportunities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('required_skills', sa.Text(), nullable=True),
    sa.Column('location_type', sa.Enum('REMOTE', 'ONSITE', 'HYBRID', name='locationtype'), nullable=False),
    sa.Column('location_address', sa.String(length=500), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('commitment_hours_per_week', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('commitment_weeks', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('available_slots', sa.Integer(), nullable=False),
    sa.Column('filled_slots', sa.Integer(), nullable=False),
    sa.Column('urgency_level', sa.Enum('NORMAL', 'HIGH', 'CRITICAL', name='urgencylevel'), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'CLOSED', 'CANCELLED', name='opportunitystatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_volunteer_opportunities_organization_id'), 'volunteer_opportunities', ['organization_id'], unique=False)
    op.create_index(op.f('ix_volunteer_opportunities_status'), 'volunteer_opportunities', ['status'], unique=False)
    op.create_table('donations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('donor_id', sa.UUID(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('is_anonymous', sa.Boolean(), nullable=False),
    sa.Column('donor_message', sa.Text(), nullable=True),
    sa.Column('transaction_id', sa.String(length=255), nullable=True),
    sa.Column('transaction_status', sa.Enum('PENDING', 'COMPLETED', 'FAILED', 'REFUNDED', name='transactionstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['donor_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_donations_campaign_id'), 'donations', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_donations_donor_id'), 'donations', ['donor_id'], unique=False)
    op.create_index(op.f('ix_donations_transaction_status'), 'donations', ['transaction_status'], unique=False)
    op.create_table('volunteer_applications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('opportunity_id', sa.UUID(), nullable=False),
    sa.Column('volunteer_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'WITHDRAWN', name='applicationstatus'), nullable=False),
    sa.Column('cover_letter', sa.Text(), nullable=True),
    sa.Column('coordinator_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['opportunity_id'], ['volunteer_opportunities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['volunteer_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('opportunity_id', 'volunteer_id', name='uq_application')
    )
    op.create_index(op.f('ix_volunteer_applications_opportunity_id'), 'volunteer_applications', ['opportunity_id'], unique=False)
    op.create_index(op.f('ix_volunteer_applications_status'), 'volunteer_applications', ['status'], unique=False)
    op.create_index(op.f('ix_volunteer_applications_volunteer_id'), 'volunteer_applications', ['volunteer_id'], unique=False)
    op.create_table('volunteer_hour_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('volunteer_id', sa.UUID(), nullable=False),
    sa.Column('opportunity_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('hours_logged', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('log_date', sa.Date(), nullable=False),
    sa.Column('check_in_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('check_out_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('log_method', sa.Enum('MANUAL', 'QR_CHECKIN', name='logmethod'), nullable=False),
    sa.Column('verification_status', sa.Enum('PENDING', 'VERIFIED', 'REJECTED', name='verificationstatus'), nullable=False),
    sa.Column('verified_by', sa.UUID(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verification_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['opportunity_id'], ['volunteer_opportunities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['verified_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['volunteer_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_volunteer_hour_logs_opportunity_id'), 'volunteer_hour_logs', ['opportunity_id'], unique=False)
    op.create_index(op.f('ix_volunteer_hour_logs_organization_id'), 'volunteer_hour_logs', ['organization_id'], unique=False)
    op.create_index(op.f('ix_volunteer_hour_logs_verification_status'), 'volunteer_hour_logs', ['verification_status'], unique=False)
    op.create_index(op.f('ix_volunteer_hour_logs_volunteer_id'), 'volunteer_hour_logs', ['volunteer_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_volunteer_hour_logs_volunteer_id'), table_name='volunteer_hour_logs')
    op.drop_index(op.f('ix_volunteer_hour_logs_verification_status'), table_name='volunteer_hour_logs')
    op.drop_index(op.f('ix_volunteer_hour_logs_organization_id'), table_name='volunteer_hour_logs')
    op.drop_index(op.f('ix_volunteer_hour_logs_opportunity_id'), table_name='volunteer_hour_logs')
    op.drop_table('volunteer_hour_logs')
    op.drop_index(op.f('ix_volunteer_applications_volunteer_id'), table_name='volunteer_applications')
    op.drop_index(op.f('ix_volunteer_applications_status'), table_name='volunteer_applications')
    op.drop_index(op.f('ix_volunteer_applications_opportunity_id'), table_name='volunteer_applications')
    op.drop_table('volunteer_applications')
    op.drop_index(op.f('ix_donations_transaction_status'), table_name='donations')
    op.drop_index(op.f('ix_donations_donor_id'), table_name='donations')
    op.drop_index(op.f('ix_donations_campaign_id'), table_name='donations')
    op.drop_table('donations')
    op.drop_index(op.f('ix_volunteer_opportunities_status'), table_name='volunteer_opportunities')
    op.drop_index(op.f('ix_volunteer_opportunities_organization_id'), table_name='volunteer_opportunities')
    op.drop_table('volunteer_opportunities')
    op.drop_index(op.f('ix_in_kind_donations_status'), table_name='in_kind_donations')
    op.drop_index(op.f('ix_in_kind_donations_organization_id'), table_name='in_kind_donations')
    op.drop_index(op.f('ix_in_kind_donations_donor_id'), table_name='in_kind_donations')
    op.drop_index(op.f('ix_in_kind_donations_category'), table_name='in_kind_donations')
    op.drop_table('in_kind_donations')
    op.drop_index(op.f('ix_campaigns_status'), table_name='campaigns')
    op.drop_index(op.f('ix_campaigns_organization_id'), table_name='campaigns')
    op.drop_table('campaigns')
    op.drop_index(op.f('ix_organizations_owner_id'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_name'), table_name='organizations')
    op.drop_table('organizations')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
