"""add_spaces_and_bookings

Revision ID: 10f59aebb15d
Revises: 687f6a6d21d1
Create Date: 2026-07-05 11:55:28.908683+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10f59aebb15d'
down_revision: Union[str, None] = '687f6a6d21d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spaces',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('host_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('space_type', sa.Enum('MEETING_ROOM', 'EVENT_HALL', 'WAREHOUSE', 'KITCHEN', 'OUTDOOR', 'OFFICE', 'COMMUNITY_CENTER', 'OTHER', name='spacetype'), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('price_per_hour', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('amenities', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'INACTIVE', name='spacestatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['host_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_spaces_city'), 'spaces', ['city'], unique=False)
    op.create_index(op.f('ix_spaces_host_id'), 'spaces', ['host_id'], unique=False)
    op.create_index(op.f('ix_spaces_space_type'), 'spaces', ['space_type'], unique=False)
    op.create_index(op.f('ix_spaces_status'), 'spaces', ['status'], unique=False)
    op.create_table('space_bookings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('space_id', sa.UUID(), nullable=False),
    sa.Column('requester_id', sa.UUID(), nullable=False),
    sa.Column('start_datetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_datetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('purpose', sa.String(length=500), nullable=False),
    sa.Column('attendee_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'COMPLETED', 'CANCELLED', name='bookingstatus'), nullable=False),
    sa.Column('host_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['requester_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['space_id'], ['spaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_space_bookings_requester_id'), 'space_bookings', ['requester_id'], unique=False)
    op.create_index(op.f('ix_space_bookings_space_id'), 'space_bookings', ['space_id'], unique=False)
    op.create_index(op.f('ix_space_bookings_status'), 'space_bookings', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_space_bookings_status'), table_name='space_bookings')
    op.drop_index(op.f('ix_space_bookings_space_id'), table_name='space_bookings')
    op.drop_index(op.f('ix_space_bookings_requester_id'), table_name='space_bookings')
    op.drop_table('space_bookings')
    op.drop_index(op.f('ix_spaces_status'), table_name='spaces')
    op.drop_index(op.f('ix_spaces_space_type'), table_name='spaces')
    op.drop_index(op.f('ix_spaces_host_id'), table_name='spaces')
    op.drop_index(op.f('ix_spaces_city'), table_name='spaces')
    op.drop_table('spaces')
    # ### end Alembic commands ###
